### ISSUE TITLE
Commit made from local to bitbucket, azure devops creates multiple pipelines

### ISSUE THREAD

**Issue by syedyakoobali** [michaelschnyder/IoTalkie#19]
Greetings

When I am done with the terraform code and push it to the Bitbucket, every time I push the code to BitBucket it creates multiple pipelines. As per my knowledge it should create only 1 pipeline and for every push it should rerun the existing pipeline. Please help me.

**Comment by syedyakoobali** [comment]
any recommendations please welcome

**Comment by michaelschnyder** [comment]
Sorry @syedyakoobali, I guess you picked the wrong repo to report this.
